---
version: "2.0"

services:
  web:
    image: kanboard/kanboard:v1.2.8
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    westcoast:
      attributes:
        datacenter: equinix-metal-ewr1
      signedBy:
        anyOf:
           - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web: 
          denom: uakt
          amount: 10

deployment:
  web:
    westcoast:
      profile: web
      count: 1