---
version: "2.0"

services:
  raptoreum:
    image: cryptoandcoffee/cpu-cpuminer-gr-avx2
    expose:
      - port: 4048
        as: 80
        proto: tcp
        to:
          - global: true
    env:
      - "ADDRESS=RMB251ZucvCNyX1yoQqsSC2wwJ3s7fHx3b"
      - "POOL=us.flockpool.com:5555"
      - "WORKER=akash"
      - "TUNE=no-tune"
      - "DONATION=0"
profiles:
  compute:
    raptoreum:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 32Mi
        storage:
          size: 128Mi
  placement:
    akash:
      pricing:
        raptoreum:
          denom: uakt
          amount: 25

deployment:
  raptoreum:
    akash:
      profile: raptoreum
      count: 1
