---
version: "2.0"

services:
  postgres:
    image: wirelos/dendrite-database:0.1.0
    params:
      storage:
        data:
          mount: /var/lib/postgresql/data
    expose:
      - port: 5432
        to:
          - service: dendrite
    env:
      - "POSTGRES_USER=dendrite"
      - "POSTGRES_PASSWORD=akash"
      - "POSTGRES_DB=dendrite"

  dendrite:
    image: wirelos/dendrite:0.1.0
    params:
      storage:
        config:
          mount: /etc/dendrite
        media:
          mount: /var/dendrite/media
    depends_on:
      - service: postgres
    env:
      - "SERVER_NAME=matrix.domain.tld"
      - "POSTGRES_PASSWORD=akash"
    expose:
      - port: 8008
        as: 80
        to:
          - global: true
      - port: 8448
        as: 443
        to:
          - global: true

profiles:
  compute:
    postgres:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta2
    dendrite:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
          - name: config
            size: 100Mi
            attributes:
              persistent: true
              class: beta2
          - name: media
            size: 10Gi
            attributes:
              persistent: true
              class: beta2

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        postgres:
          denom: uakt
          amount: 10000
        dendrite:
          denom: uakt
          amount: 10000

deployment:
  postgres:
    akash:
      profile: postgres
      count: 1
  dendrite:
    akash:
      profile: dendrite
      count: 1
