---
version: "2.0"

services:
  myetherwallet:
    image: jialei12138/myetherwallet:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    myetherwallet:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash1nxq8gmsw2vlz3m68qvyvcf3kh6q269ajvqw6y0"
      pricing:
        myetherwallet: 
          denom: uakt
          amount: 100

deployment:
  myetherwallet:
    akash:
      profile: myetherwallet
      count: 1
