---
version: "2.0"

services:
  wordpress:
    image: wordpress 
    expose:
      - port: 80
        to:
          - global: true

profiles:
  compute:
    wordpress:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 2Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash1nxq8gmsw2vlz3m68qvyvcf3kh6q269ajvqw6y0"
      pricing:
        wordpress: 
          denom: uakt
          amount: 100

deployment:
  wordpress:
    akash:
      profile: wordpress
      count: 1
